# Generated by Django 3.0.8 on 2022-11-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_chapter_parent2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='parent2',
        ),
    ]
